### ISSUE TITLE
Markdownlinter line-length

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-aa-cookiecutter#8]
@turnerm @caldwellst  We have a markdownlinter that forces us to keep lines to 79 characters in notebooks. I have been finding this very irritating and would argue to remove that rule. What do you think? Or do you know a way to automatically wrap them at 79?

**Comment by turnerm** [comment]
Aha, yeah I guess I've become desensitized to broken up sentences due to too much LaTeX. But happy to increase a bit, how does 120 sound?

**Comment by Tinkaa** [comment]
Sounds like a deal ;)

**Comment by caldwellst** [comment]
Sounds good to me!

**Comment by Tinkaa** [comment]
Since increasing line-length is ugly, see #9 , we will stick to line-length of 79 for now.
